Trait {
	#name : #GeoSymbologyManagerServices,
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #'GeoView-Symbology'
}

{ #category : #'services - symbology manager' }
GeoSymbologyManagerServices >> getCurrentSymbology [
]

{ #category : #'services - symbology manager' }
GeoSymbologyManagerServices >> getSymbol: aKey [

]

{ #category : #'services - symbology manager' }
GeoSymbologyManagerServices >> setCurrentSymbology: aKey [

]
