"
I am layer events for Geoplot.
"
Trait {
	#name : #GeoViewManagerLayerEvents,
	#traits : 'MolComponentEvents',
	#classTraits : 'MolComponentEvents classTrait',
	#category : #'GeoView-Core'
}

{ #category : #events }
GeoViewManagerLayerEvents >> layerAdded: aKey view: aGeoViewManagerKey [
]

{ #category : #events }
GeoViewManagerLayerEvents >> layerDeleted: aKey view: aGeoViewManagerKey [
]

{ #category : #events }
GeoViewManagerLayerEvents >> layerUpdated: aKey view: aGeoViewManagerKey [
]
