"
I am a view Projection, convert cartesian coordinates to graphic device coordinates.
"
Trait {
	#name : #GeoViewProjection,
	#category : #'GeoView-ViewProjection'
}

{ #category : #accessing }
GeoViewProjection >> altitudeInMeters [
]

{ #category : #accessing }
GeoViewProjection >> altitudeInMeters: aNumber [
]

{ #category : #accessing }
GeoViewProjection >> cartesianCenter: aCartesianCoordinates [
]

{ #category : #accessing }
GeoViewProjection >> key [
]

{ #category : #accessing }
GeoViewProjection >> projCartToPixel: aCartesianCoordinates [
]

{ #category : #accessing }
GeoViewProjection >> projPixelToCart: aPoint [
]

{ #category : #accessing }
GeoViewProjection >> updateResolution: aViewSize [
]
