"
I am geoplot manager geoobject services.
"
Trait {
	#name : #GeoViewManagerGeoObjectsServices,
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #'GeoView-Core'
}

{ #category : #'geobjects aur' }
GeoViewManagerGeoObjectsServices >> addGeoObject: aGeoObject [
]

{ #category : #'geobjects aur' }
GeoViewManagerGeoObjectsServices >> addGeoObjects: aGeoObjectList [
]

{ #category : #'geobjects aur' }
GeoViewManagerGeoObjectsServices >> removeGeoObject: aGeoObject [
]

{ #category : #'geobjects aur' }
GeoViewManagerGeoObjectsServices >> removeGeoObjects: aGeoObjectList [
]

{ #category : #'geobjects aur' }
GeoViewManagerGeoObjectsServices >> updateGeoObject: aGeoObject [
]

{ #category : #'geobjects aur' }
GeoViewManagerGeoObjectsServices >> updateGeoObjects: aGeoObjectList [
]
