"
I am the parameters of the GeoplotManager.
"
Trait {
	#name : #GeoViewManagerParameters,
	#traits : 'MolComponentParameters',
	#classTraits : 'MolComponentParameters classTrait',
	#category : #'GeoView-Core'
}

{ #category : #'parameters - event strategy' }
GeoViewManagerParameters >> addEventBehavior: aGeoViewEventBehavior [
]

{ #category : #'parameters - event strategy' }
GeoViewManagerParameters >> addEventBehaviorAtFirst: aGeoViewEventBehavior [
]

{ #category : #'parameters - event strategy' }
GeoViewManagerParameters >> deleteEventBehavior: aGeoViewEventBehavior [
]

{ #category : #'parameters - event strategy' }
GeoViewManagerParameters >> deleteEventBehaviors [
]

{ #category : #'parameters - event strategy' }
GeoViewManagerParameters >> getEventBehaviors [
]

{ #category : #'parameters - event strategy' }
GeoViewManagerParameters >> setEventBehaviors: anEventBehaviorList [
]

{ #category : #'parameters - selection manager' }
GeoViewManagerParameters >> setSelectionManager: aSmockSelectionManager [
]
