"
I am the ProjectionManager Services.
"
Trait {
	#name : #MapProjectionManagerServices,
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #'GeoView-MapProjection'
}

{ #category : #projection }
MapProjectionManagerServices >> getProjection [
]

{ #category : #projection }
MapProjectionManagerServices >> setProjection: aProjection [
]

{ #category : #projection }
MapProjectionManagerServices >> updateProjection: aProjection [
]
