Trait {
	#name : #TGeoViewHandleDShapes,
	#category : #'GeoView-Core'
}

{ #category : #'API -- DShapes' }
TGeoViewHandleDShapes >> addDShape: aDShape [

	self explicitRequirement
]

{ #category : #'API -- DShapes' }
TGeoViewHandleDShapes >> addDShapes: aDShapeList [

	self explicitRequirement
]

{ #category : #'API -- DShapes' }
TGeoViewHandleDShapes >> haveDShapeKey: aKey [

	self explicitRequirement
]

{ #category : #'API -- DShapes' }
TGeoViewHandleDShapes >> removeDShape: aDShape [

	self explicitRequirement
]

{ #category : #'API -- DShapes' }
TGeoViewHandleDShapes >> removeDShapes: aDShapeList [

	self explicitRequirement
]

{ #category : #'API -- DShapes' }
TGeoViewHandleDShapes >> updateDShape: aDShape [

	self explicitRequirement
]

{ #category : #'API -- DShapes' }
TGeoViewHandleDShapes >> updateDShapes: aDShapeList [

	self explicitRequirement
]
