"
I am a view Projection, convert cartesian coordinates to graphic device coordinates.
"
Trait {
	#name : #TGeoViewGraphicProjection,
	#category : #'GeoView-Projections'
}

{ #category : #accessing }
TGeoViewGraphicProjection >> altitudeInMeters [
]

{ #category : #accessing }
TGeoViewGraphicProjection >> altitudeInMeters: aNumber [
]

{ #category : #accessing }
TGeoViewGraphicProjection >> cartesianCenter: aCartesianCoordinates [
]

{ #category : #accessing }
TGeoViewGraphicProjection >> key [
]

{ #category : #projection }
TGeoViewGraphicProjection >> projCartToPixel: aCartesianCoordinates [
]

{ #category : #projection }
TGeoViewGraphicProjection >> projPixelToCart: aPoint [
]

{ #category : #accessing }
TGeoViewGraphicProjection >> updateResolution: aViewSize [
]
