"
I am Map Projection, convert absolute coordinates to cartesian coordinates.
"
Trait {
	#name : #TGeoViewMapProjection,
	#category : #'GeoView-Projections'
}

{ #category : #accessing }
TGeoViewMapProjection >> key [
]

{ #category : #accessing }
TGeoViewMapProjection >> projCartToLatLon: aCartesianCoordinates [
]

{ #category : #accessing }
TGeoViewMapProjection >> projLatLonToCart: anAbsoluteCoordinates [
]
