"
I am geoplot manager events
"
Trait {
	#name : #GeoViewManagerEvents,
	#traits : 'MolComponentEvents',
	#classTraits : 'MolComponentEvents classTrait',
	#category : #'GeoView-Molecule-Core'
}

{ #category : #'events - map projection' }
GeoViewManagerEvents >> mapProjectionHasChanged: aMapProjection [
]

{ #category : #'events - map projection' }
GeoViewManagerEvents >> mapProjectionUpdated: aMapProjection [
]
