"
I am layer services for Geoplot.
"
Trait {
	#name : #GeoViewManagerLayerServices,
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #'GeoView-Molecule'
}

{ #category : #'services - layer creation' }
GeoViewManagerLayerServices >> addLayer: aLayer [
]

{ #category : #'services - layer creation' }
GeoViewManagerLayerServices >> createAndAddGeoObjectsLayer: aKey [
]

{ #category : #'services - layer accessing' }
GeoViewManagerLayerServices >> getLayer: aKey [
]

{ #category : #'services - layer configuration' }
GeoViewManagerLayerServices >> getLayerLevel: aKey [
]

{ #category : #'services - layer accessing' }
GeoViewManagerLayerServices >> getLayers [
]

{ #category : #'services - layer deletion' }
GeoViewManagerLayerServices >> removeAllLayers [
]

{ #category : #'services - layer deletion' }
GeoViewManagerLayerServices >> removeLayer: aKey [
]

{ #category : #'services - layer configuration' }
GeoViewManagerLayerServices >> setLevel: anInteger forLayer: aKey [
]
