"
I am geoplot manager geoobject services.
"
Trait {
	#name : #GeoViewManagerObjectsServices,
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #'GeoView-Molecule-Contract'
}

{ #category : #'services - object' }
GeoViewManagerObjectsServices >> addObject: aGeoObject [
]

{ #category : #'services - object' }
GeoViewManagerObjectsServices >> addObjects: aGeoObjectList [
]

{ #category : #'services - object' }
GeoViewManagerObjectsServices >> haveObjectIndex: anIndex [
]

{ #category : #'services - object' }
GeoViewManagerObjectsServices >> removeObject: aGeoObject [
]

{ #category : #'services - object' }
GeoViewManagerObjectsServices >> removeObjects: aGeoObjectList [
]

{ #category : #'services - object' }
GeoViewManagerObjectsServices >> updateObject: aGeoObject [
]

{ #category : #'services - object' }
GeoViewManagerObjectsServices >> updateObjects: aGeoObjectList [
]
