"
I am layer events for Geoplot.
"
Trait {
	#name : #GeoViewManagerLayerEvents,
	#traits : 'MolComponentEvents',
	#classTraits : 'MolComponentEvents classTrait',
	#category : #'GeoView-Molecule-Core'
}

{ #category : #events }
GeoViewManagerLayerEvents >> geoViewLayerAdded: aKey in: aGeoViewManagerKey [
]

{ #category : #events }
GeoViewManagerLayerEvents >> geoViewLayerRemoved: aKey in: aGeoViewManagerKey [
]

{ #category : #events }
GeoViewManagerLayerEvents >> geoViewLayerUpdated: aKey in: aGeoViewManagerKey [
]
