name: 'CI'

env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  pull_request: #necessary to display "check" step in a PR
    types: [labeled]
  workflow_dispatch: #manual trigger

jobs:
  test:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.label.name == 'run-ci')
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        smalltalk: [ Pharo64-12, Pharo64-13 ]
        ston: [ .smalltalkci.default.ston, .smalltalkci.core.ston ]
    runs-on: ${{ matrix.os }}
    name: >
      ${{ matrix.smalltalk }} • ${{ matrix.ston == '.smalltalkci.default.ston' && 'Full' || 'Core' }} • ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}

      - name: Run ${{ matrix.ston == '.smalltalkci.default.ston' && 'Full' || 'Core' }} tests
        run: smalltalkci -s ${{ matrix.smalltalk }} ${{ matrix.ston }}
        shell: bash
        timeout-minutes: 30
